### ISSUE TITLE
is it support swift3?

### ISSUE THREAD

**Issue by CoderYLZhang** [hemantasapkota/GCDTimer#5]
<img width="1371" alt="ffeb15bd-d3ae-46b1-b76e-0eaf033f635e" src="https://cloud.githubusercontent.com/assets/13221319/20887277/e70ba26a-bb34-11e6-92fe-91f876e0ead4.png">
i convert it to swift3,show error
what wrong with it?

**Comment by hemantasapkota** [comment]
Hi, You can checkout the ```swift3``` branch. I'll merge with master when I get the time.

Thanks

**Comment by CoderYLZhang** [comment]
thank you

**Comment by hemantasapkota** [comment]
Merged with master.
